// Generated by lsc from lattice.ts

function flowRankIsPermitted(sourceRank: int, destinationRank: int): bool
  requires (sourceRank >= 0)
  requires (sourceRank <= 4)
  requires (destinationRank >= 0)
  requires (destinationRank <= 4)
{
  (sourceRank <= destinationRank)
}

lemma flowRankIsPermitted_ensures(sourceRank: int, destinationRank: int)
  requires (sourceRank >= 0)
  requires (sourceRank <= 4)
  requires (destinationRank >= 0)
  requires (destinationRank <= 4)
  ensures (flowRankIsPermitted(sourceRank, destinationRank) == (sourceRank <= destinationRank))
{
}
