import type { IncidentDemo } from './domain'

export const demo: IncidentDemo = {
  incident: {
    id: 'INC-1042',
    title: 'Payments API elevated error rate',
    severity: 'high',
    status: 'resolved',
    service: 'payments-api',
    startedAt: '2026-08-12T09:58:00Z',
    owner: 'Commerce SRE',
    summary:
      'Instance payments-api-03 degraded while payment authorizations timed out. The governed agent restarted exactly that instance after approval, then verified service health.',
  },
  events: [
    {
      id: 'evt-01',
      at: '09:58:04',
      kind: 'observation',
      actor: 'Sentinel',
      title: 'Incident and telemetry read',
      detail: 'get_incident, query_metrics, and query_logs identified degraded instance payments-api-03.',
      outcome: 'safe',
    },
    {
      id: 'evt-02',
      at: '09:58:18',
      kind: 'threat-blocked',
      actor: 'Governed agent',
      title: 'Indirect prompt injection treated as data',
      detail:
        'The simulator marked the log entry as untrusted content. It was retained as incident evidence and did not become an authorized action.',
      outcome: 'blocked',
    },
    {
      id: 'evt-03',
      at: '09:58:21',
      kind: 'containment',
      actor: 'Governance operator',
      title: 'Application containment activated',
      detail: 'The governed gateway denied new execution while the suspicious input and deployment state were reviewed.',
      outcome: 'contained',
    },
    {
      id: 'evt-04',
      at: '09:58:31',
      kind: 'recovery',
      actor: 'Governance operator',
      title: 'Known-good state re-attested',
      detail: 'Identity, policy, tool registry, and deployment digest matched the approved baseline; diagnostic reads were restored first.',
      outcome: 'recovering',
    },
    {
      id: 'evt-05',
      at: '09:58:38',
      kind: 'recovery',
      actor: 'Maya Chen',
      title: 'Operational access restored',
      detail: 'The incident commander signed off the root cause and restored write eligibility under normal approval policy.',
      outcome: 'restored',
    },
    {
      id: 'evt-06',
      at: '09:58:42',
      kind: 'plan-verified',
      actor: 'Plan verifier',
      title: 'Restart plan verified',
      detail: 'service.restart via restart_service targets only payments-api-03 and requires incident-commander approval.',
      outcome: 'safe',
    },
    {
      id: 'evt-07',
      at: '10:00:09',
      kind: 'approval',
      actor: 'Maya Chen',
      title: 'Exact change approved',
      detail: 'Approval bound to the immutable plan hash, production target, and 10-minute window.',
      outcome: 'approved',
    },
    {
      id: 'evt-08',
      at: '10:00:12',
      kind: 'lease',
      actor: 'Governed gateway',
      title: 'Task-scoped capability lease issued',
      detail: 'Verified Remediate intent received a 90-second, one-use lease bound to the exact agent, plan, action digest, target, and policy version.',
      outcome: 'approved',
    },
    {
      id: 'evt-09',
      at: '10:00:15',
      kind: 'execution',
      actor: 'Execution gateway',
      title: 'Approved remediation executed',
      detail: 'restart_service executed once for payments-api / payments-api-03. No other write was permitted.',
      outcome: 'approved',
    },
    {
      id: 'evt-10',
      at: '10:00:18',
      kind: 'evidence',
      actor: 'Sentinel',
      title: 'Health verification passed',
      detail: 'get_service_health confirmed payments-api and all three instances are healthy.',
      outcome: 'safe',
    },
  ],
  checks: [
    { id: 'check-1', label: 'Registered tool', evidence: 'restart_service · service.restart', status: 'passed' },
    { id: 'check-2', label: 'Target scope', evidence: 'payments-api · payments-api-03', status: 'passed' },
    { id: 'check-3', label: 'Compensation', evidence: 'restore_service_state · service.restore', status: 'passed' },
    { id: 'check-4', label: 'Untrusted log instruction', evidence: 'Not an approved capability or tool call', status: 'blocked' },
  ],
  approval: {
    id: 'APR-7F31',
    status: 'approved',
    action: 'Restart degraded service instance',
    target: 'production / payments-api / payments-api-03',
    command: 'restart_service(serviceId="payments-api", instanceId="payments-api-03")',
    compensation: 'restore_service_state(serviceId="payments-api", instanceId="payments-api-03", previousHealth="Degraded", sourceVersion=1)',
    changeHash: 'sha256:7f31d9e8…a42c',
    requestedBy: 'Governed agent · plan-1042',
    approvedBy: 'Maya Chen · Incident commander',
    approvedAt: '2026-08-12 10:00:09 UTC',
    expiresAt: '2026-08-12 10:05:00 UTC',
    constraints: ['Single execution', 'Expected resource version enforced', 'Verify health after restart'],
  },
  capabilityLease: {
    id: 'LEASE-1042-01',
    intentSource: 'Structured verified plan',
    promptRole: 'Advisory only · cannot grant access',
    intent: 'remediate',
    scope: 'restart_service · payments-api / payments-api-03 · production',
    issuedAt: '2026-08-12 10:00:12 UTC',
    expiresAt: '2026-08-12 10:01:42 UTC',
    maximumUses: 1,
    consumedUses: 1,
    state: 'completed',
  },
  policy: {
    policyVersion: 'v3.14.2',
    enforcement: 'enforced',
    containmentMode: 'operational',
    privileges: [
      'get_incident · incident.read',
      'query_metrics · telemetry.metrics.read',
      'query_logs · telemetry.logs.read',
      'get_service_health · service.health.read',
      'restart_service · service.restart',
      'restore_service_state · service.restore',
    ],
    lastEvaluatedAt: '10:00:15 UTC',
    reattestation: {
      artifactDigest: 'aaaaaaaa…aaaaaaaa',
      knownGoodVersion: 'agent-image:sha256:known-good',
      attestedBy: 'operator@example.test',
    },
    recoverySignOff: {
      actor: 'Maya Chen · Incident commander',
      rootCause: 'Removed the untrusted integration and verified the known-good deployment.',
    },
  },
  audit: [
    { sequence: 8041, at: '09:58:18', event: 'log.untrusted_content_observed', digest: '9a61…e2c0', previousDigest: '482b…110e' },
    { sequence: 8042, at: '09:58:21', event: 'containment.activate', digest: '105c…ab91', previousDigest: '9a61…e2c0' },
    { sequence: 8043, at: '09:58:31', event: 'recovery.reattest', digest: '73b8…ef22', previousDigest: '105c…ab91' },
    { sequence: 8044, at: '09:58:38', event: 'recovery.restore', digest: '0fd4…c812', previousDigest: '73b8…ef22' },
    { sequence: 8045, at: '09:58:42', event: 'plan.verified', digest: 'c428…fb7d', previousDigest: '0fd4…c812' },
    { sequence: 8046, at: '10:00:09', event: 'approval.granted', digest: 'e913…48aa', previousDigest: 'c428…fb7d' },
    { sequence: 8047, at: '10:00:12', event: 'capability_lease.issued', digest: 'bb09…34f1', previousDigest: 'e913…48aa' },
    { sequence: 8048, at: '10:00:13', event: 'capability_lease.consumed', digest: 'a777…290c', previousDigest: 'bb09…34f1' },
    { sequence: 8049, at: '10:00:15', event: 'capability_lease.completed', digest: 'c19a…7d40', previousDigest: 'a777…290c' },
    { sequence: 8050, at: '10:00:18', event: 'get_service_health.verified', digest: 'aa18…61c2', previousDigest: 'c19a…7d40' },
  ],
}
