import type { IncidentDemo } from './domain'

export const demo: IncidentDemo = {
  incident: {
    id: 'INC-1042',
    title: 'Payments API elevated error rate',
    severity: 'high',
    status: 'resolved',
    service: 'payments-api',
    startedAt: '2026-08-12T09:58:00Z',
    owner: 'Commerce SRE',
    summary:
      'Instance payments-api-03 degraded while payment authorizations timed out. The governed agent restarted exactly that instance after approval, then verified service health.',
  },
  events: [
    {
      id: 'evt-01',
      at: '09:58:04',
      kind: 'observation',
      actor: 'Sentinel',
      title: 'Incident and telemetry read',
      detail: 'get_incident, query_metrics, and query_logs identified degraded instance payments-api-03.',
      outcome: 'safe',
    },
    {
      id: 'evt-02',
      at: '09:58:18',
      kind: 'threat-blocked',
      actor: 'Governed agent',
      title: 'Indirect prompt injection treated as data',
      detail:
        'The simulator marked the log entry as untrusted content. It was retained as incident evidence and did not become an authorized action.',
      outcome: 'blocked',
    },
    {
      id: 'evt-03',
      at: '09:58:42',
      kind: 'plan-verified',
      actor: 'Plan verifier',
      title: 'Restart plan verified',
      detail: 'service.restart via restart_service targets only payments-api-03 and requires incident-commander approval.',
      outcome: 'safe',
    },
    {
      id: 'evt-04',
      at: '10:00:09',
      kind: 'approval',
      actor: 'Maya Chen',
      title: 'Exact change approved',
      detail: 'Approval bound to the immutable plan hash, production target, and 10-minute window.',
      outcome: 'approved',
    },
    {
      id: 'evt-05',
      at: '10:00:15',
      kind: 'execution',
      actor: 'Execution gateway',
      title: 'Approved remediation executed',
      detail: 'restart_service executed once for payments-api / payments-api-03. No other write was permitted.',
      outcome: 'approved',
    },
    {
      id: 'evt-06',
      at: '10:00:18',
      kind: 'evidence',
      actor: 'Sentinel',
      title: 'Health verification passed',
      detail: 'get_service_health confirmed payments-api and all three instances are healthy.',
      outcome: 'safe',
    },
  ],
  checks: [
    { id: 'check-1', label: 'Registered tool', evidence: 'restart_service · service.restart', status: 'passed' },
    { id: 'check-2', label: 'Target scope', evidence: 'payments-api · payments-api-03', status: 'passed' },
    { id: 'check-3', label: 'Compensation', evidence: 'restore_service_state · service.restore', status: 'passed' },
    { id: 'check-4', label: 'Untrusted log instruction', evidence: 'Not an approved capability or tool call', status: 'blocked' },
  ],
  approval: {
    id: 'APR-7F31',
    status: 'approved',
    action: 'Restart degraded service instance',
    target: 'production / payments-api / payments-api-03',
    command: 'restart_service(serviceId="payments-api", instanceId="payments-api-03")',
    compensation: 'restore_service_state(serviceId="payments-api", instanceId="payments-api-03", previousHealth="Degraded", sourceVersion=1)',
    changeHash: 'sha256:7f31d9e8…a42c',
    requestedBy: 'Governed agent · plan-1042',
    approvedBy: 'Maya Chen · Incident commander',
    approvedAt: '2026-08-12 10:00:09 UTC',
    expiresAt: '2026-08-12 10:05:00 UTC',
    constraints: ['Single execution', 'Expected resource version enforced', 'Verify health after restart'],
  },
  policy: {
    policyVersion: 'v3.14.2',
    enforcement: 'enforced',
    killSwitch: 'armed',
    privileges: [
      'get_incident · incident.read',
      'query_metrics · telemetry.metrics.read',
      'query_logs · telemetry.logs.read',
      'get_service_health · service.health.read',
      'restart_service · service.restart',
      'restore_service_state · service.restore',
    ],
    lastEvaluatedAt: '10:00:15 UTC',
  },
  audit: [
    { sequence: 8041, at: '09:58:18', event: 'log.untrusted_content_observed', digest: '9a61…e2c0', previousDigest: '482b…110e' },
    { sequence: 8042, at: '09:58:42', event: 'plan.verified', digest: 'c428…fb7d', previousDigest: '9a61…e2c0' },
    { sequence: 8043, at: '10:00:09', event: 'approval.granted', digest: 'e913…48aa', previousDigest: 'c428…fb7d' },
    { sequence: 8044, at: '10:00:15', event: 'restart_service.executed', digest: 'bb09…34f1', previousDigest: 'e913…48aa' },
    { sequence: 8045, at: '10:00:18', event: 'get_service_health.verified', digest: 'aa18…61c2', previousDigest: 'bb09…34f1' },
  ],
}
